almacen/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from almacen.views import registrar_inventario_inicial,registrar_ingreso,busquedaSuministro, Inicio, CrearTipoIngreso, CrearAlmacen, CrearZona, CrearSuministro,CrearTipoUnidad,CrearTipoStock, CrearGrupoSuministros, upload_file, ListadoSuministros, DetalleSuministro, ModificarSuministro, KardexSuministro,ReporteKardexSuministro

urlpatterns = patterns('',
	url(r'^$', Inicio.as_view(), name="inicio"),
	url(r'^registrar_inventario_inicial/$',registrar_inventario_inicial, name="registrar_inventario_inicial"),
	url(r'^registrar_ingreso/$',registrar_ingreso, name="registrar_ingreso"),
	url(r'^busquedaSuministro/$',busquedaSuministro, name="busquedaSuministro"),
	url(r'^crear_tipo_ingreso/$', CrearTipoIngreso.as_view(), name="crear_tipo_ingreso"),
	url(r'^crear_almacen/$', CrearAlmacen.as_view(), name="crear_almacen"),
	url(r'^crear_zona/$', CrearZona.as_view(), name="crear_zona"),
	url(r'^crear_suministro/$', CrearSuministro.as_view(), name="crear_suministro"),
	url(r'^crear_tipo_unidad/$', CrearTipoUnidad.as_view(), name="crear_tipo_unidad"),
	url(r'^crear_tipo_stock/$', CrearTipoStock.as_view(), name="crear_tipo_stock"),
	url(r'^crear_grupo_suministros/$', CrearGrupoSuministros.as_view(), name="crear_grupo_suministros"),
	url(r'^upload_file/', upload_file, name="upload_file"),
	url(r'^reporte_suministros/$', ListadoSuministros.as_view(), name="reporte_suministros"),
	url(r'^suministros/(?P<pk>\d+)/$',DetalleSuministro.as_view(), name="detalle_suministro"),
	url(r'^modificar/(?P<pk>\d+)/$',ModificarSuministro.as_view(), name="modificar_suministro"),
	url(r'^kardex_suministro/$', KardexSuministro.as_view(), name="kardex_suministro"),
	url(r'^reporte_kardex_suministro/$', ReporteKardexSuministro.as_view(), name="reporte_kardex_suministro"),
)

intix/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'intix.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^almacen/', include('almacen.urls',namespace='almacen')),
    url(r'^', include('usuarios.urls',namespace='usuarios')),
)

almacen/forms.py
from django import forms
from django.forms import ModelForm
from almacen.models import Tipo, Almacen, Zona, Suministro, GrupoSuministros
from usuarios.models import Empresa

class UploadForm(forms.Form):
    docfile = forms.FileField(label='Selecciona un archivo')

class TipoIngresoForm(forms.ModelForm):

    class Meta:
        model = Tipo
        fields =['codigo','descripcion_valor']

    def __init__(self, *args, **kwargs):
        self.tabla = "tipo_Ingreso"
        self.descripcion_campo = "tipo_Ingreso"
        super(TipoIngresoForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.instance.tabla = self.tabla
        self.instance.descripcion_campo = self.descripcion_campo
        super(TipoIngresoForm, self).save(*args, **kwargs)

class TipoUnidadForm(forms.ModelForm):

    class Meta:
        model = Tipo
        fields =['codigo','descripcion_valor']

    def __init__(self, *args, **kwargs):
        self.tabla = "tipo_unidad_medida"
        self.descripcion_campo = "tipo_unidad_medida"
        super(TipoUnidadForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.instance.tabla = self.tabla
        self.instance.descripcion_campo = self.descripcion_campo
        super(TipoUnidadForm, self).save(*args, **kwargs)        

class TipoStockForm(forms.ModelForm):

    class Meta:
        model = Tipo
        fields =['codigo','descripcion_valor']

    def __init__(self, *args, **kwargs):
        self.tabla = "tipo_stock"
        self.descripcion_campo = "tipo_stock"
        super(TipoStockForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.instance.tabla = self.tabla
        self.instance.descripcion_campo = self.descripcion_campo
        super(TipoStockForm, self).save(*args, **kwargs)  

class AlmacenForm(forms.ModelForm):

    def __init__(self, empresa,*args, **kwargs):
        super(AlmacenForm, self).__init__(*args, **kwargs)
        self.fields['empresa'].queryset = Empresa.objects.filter(codigo=empresa.codigo)        

    class Meta:
        model = Almacen
        fields =['descripcion','empresa','zona']

class ZonaForm(forms.ModelForm):

    class Meta:
        model = Zona
        fields =['descripcion']

class GrupoSuministrosForm(forms.ModelForm):

    class Meta:
        model = GrupoSuministros
        fields = ['descripcion','ctaalm','ctacomp']

        

class SuministroForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(SuministroForm, self).__init__(*args, **kwargs)
        self.fields['tipo_unidad_medida'].queryset = Tipo.objects.filter(tabla="tipo_unidad_medida")
        self.fields['tipo_stock'].queryset = Tipo.objects.filter(tabla="tipo_stock")

    class Meta:
        model = Suministro
        fields =['descripcion', 'precio_mercado', 'grupo_suministros','tipo_unidad_medida','tipo_stock']        

almacen/views.py
from django.shortcuts import render
from almacen.models import Tipo, Almacen, Suministro, Movimiento, DetalleMovimiento, GrupoSuministros, Zona, CuentaContable, Archivo, SuministroEmpresa, Kardex
from usuarios.models import Usuario
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
import json
from django.db import connection
import datetime,time
from django.views.generic import TemplateView, FormView, View, ListView, DetailView, UpdateView
from almacen.forms import TipoIngresoForm, AlmacenForm, ZonaForm, SuministroForm, TipoUnidadForm, TipoStockForm, GrupoSuministrosForm, UploadForm
import csv
from django.db.models import Max, Sum
from decimal import Decimal

def registrar_inventario_inicial(request):
	almacenes = Almacen.objects.all()
	t_mov='I'
	try: 
		tipo_movimiento = Tipo.objects.get(tabla="tipo_Movimiento",codigo=t_mov)
	except Tipo.DoesNotExist:
		tipo_movimiento = Tipo(tabla='tipo_Movimiento',descripcion_campo='tipo_Movimiento',codigo=t_mov,descripcion_valor='INGRESO')
		tipo_movimiento.save()
	t_ing = 'I00'
	try: 
		tipo_ingreso = Tipo.objects.get(tabla='tipo_Ingreso',codigo=t_ing)
	except Tipo.DoesNotExist:
		tipo_ingreso = Tipo(tabla='tipo_Ingreso',descripcion_campo='tipo_Ingreso',codigo=t_ing,descripcion_valor='INGRESO POR INVENTARIO INICIAL')
		tipo_ingreso.save()

	if request.method == 'POST':
		r_almacen = request.POST['almacenes']
		almacen = Almacen.objects.get(id=r_almacen)
		r_fecha = request.POST['fecha']
		anio = r_fecha[6:]
		mes = r_fecha[3:5]
		dia = int(r_fecha[0:2])
		fecha = datetime.date(int(anio),int(mes),dia)
		cdetalles = int(request.POST['cdetalles'])
		zona = almacen.zona
		empresa = almacen.empresa
		cod_movimiento=obtener_codigo_movimiento(tipo_movimiento, zona, anio, empresa)
		movimiento = Movimiento(cod_movimiento,tipo_movimiento.id,tipo_ingreso.id)
		movimiento.anio=anio
		movimiento.mes = mes
		movimiento.almacen = almacen
		movimiento.fecha_operacion=fecha
		movimiento.usuario = request.user.usuario
		movimiento.observacion = 'Inventario inicial'
		movimiento.save()
		for i in range(cdetalles):
			id="tblDetalle_id_"+str(i+1)
			cant="tblDetalle_cantidad_"+str(i+1)
			prec="tblDetalle_precio_"+str(i+1)
			val="tblDetalle_valor_"+str(i+1)		
			id_suministro = request.POST[id]
			suministro = Suministro.objects.get(codigo=id_suministro)
			grupo_suministros = GrupoSuministros.objects.get(codigo=suministro.grupo_suministros.codigo)
			cantidad = Decimal(request.POST[cant])			
			precio= Decimal(request.POST[prec])
			valor = Decimal(request.POST[val])
			detalle = DetalleMovimiento(nro_detalle=i+1,movimiento=movimiento,suministro=suministro)
			detalle.cantidad=cantidad
			detalle.precio=precio
			detalle.valor = valor
			detalle.save()
			return HttpResponseRedirect(reverse('almacen:inicio'))
	context = {'almacenes':almacenes}
	return render(request, 'inventario_inicial.html', context)

def registrar_ingreso(request):	
	tipos_ingreso = Tipo.objects.exclude(codigo='I00').filter(tabla="tipo_Ingreso")
	t_mov='I'
	try: 
		tipo_movimiento = Tipo.objects.get(tabla="tipo_Movimiento",codigo=t_mov)
	except Tipo.DoesNotExist:
		tipo_movimiento = Tipo(tabla='tipo_Movimiento',descripcion_campo='tipo_Movimiento',codigo=t_mov,descripcion_valor='INGRESO')
		tipo_movimiento.save()
	if not tipos_ingreso:
		return HttpResponseRedirect(reverse('almacen:crear_tipo_ingreso'))	
	almacenes = Almacen.objects.filter()		
	tipos_documento = Tipo.objects.filter(tabla="tipo_Documento")
	if request.method == 'POST':
		tipo_ingreso=int(request.POST['tipos_ingreso'])
		tipo_documento=request.POST['tipos_documento']
		serie = request.POST['serie']
		numero = request.POST['numero']
		r_almacen = request.POST['almacenes']
		almacen = Almacen.objects.get(id=r_almacen)
		r_fecha = request.POST['fecha']
		anio = r_fecha[6:]
		mes = r_fecha[3:5]
		dia = int(r_fecha[0:2])
		fecha = datetime.date(int(anio),int(mes),dia)
		cdetalles = int(request.POST['cdetalles'])
		zona = almacen.zona
		empresa = almacen.empresa
		cod_movimiento=obtener_codigo_movimiento(tipo_movimiento, zona, anio, empresa)
		movimiento = Movimiento(cod_movimiento,tipo_movimiento.id,tipo_ingreso,tipo_documento,serie)
		movimiento.anio=anio
		movimiento.mes = mes
		movimiento.almacen = almacen
		movimiento.fecha_operacion=fecha
		movimiento.numero = numero
		movimiento.usuario = request.user.usuario
		movimiento.save()
		for i in range(cdetalles):
			id="tblDetalle_id_"+str(i+1)
			cant="tblDetalle_cantidad_"+str(i+1)
			prec="tblDetalle_precio_"+str(i+1)
			val="tblDetalle_valor_"+str(i+1)		
			id_suministro = request.POST[id]
			suministro = Suministro.objects.get(codigo=id_suministro)
			grupo_suministros = GrupoSuministros.objects.get(codigo=suministro.grupo_suministros.codigo)
			cantidad = Decimal(request.POST[cant])
			precio= Decimal(request.POST[prec])
			valor = Decimal(request.POST[val])
			detalle = DetalleMovimiento(nro_detalle=i+1,movimiento=movimiento,suministro=suministro)
			detalle.cantidad=cantidad
			detalle.precio=precio
			detalle.valor = valor
			detalle.save()
		#return HttpResponseRedirect(reverse('almacen:registrar_ingreso'))

	context = {'tipos_ingreso':tipos_ingreso,'almacenes':almacenes,'tipos_documento':tipos_documento}
	return render(request, 'ingresar_movimiento.html', context)

def busquedaSuministro(request):
	if request.is_ajax():
		q = request.GET.get('term', '')
		suministros = Suministro.objects.filter(descripcion__icontains = q )[:20]	
		results = []
		for suministro in suministros:
			suministro_json = {}
			suministro_json['id'] = suministro.codigo
			suministro_json['label'] = suministro.descripcion
			suministro_json['value'] = suministro.descripcion
			unidad = Tipo.objects.get(id=suministro.tipo_unidad_medida.id,tabla='tipo_unidad_medida')			
			suministro_json['unidad'] = unidad.descripcion_valor
			suministro_json['precio'] = str(suministro.precio_mercado)			
			results.append(suministro_json)			
		data = json.dumps(results)		
	else:
		data = 'fail'
	mimetype = 'application/json'
	return HttpResponse(data, mimetype)

def obtener_codigo_movimiento(tipo, zona, anio, empresa):
	mov_ant = Movimiento.objects.filter(tipo_movimiento=tipo.id, almacen__zona=zona, fecha_operacion__year=anio,almacen__empresa=empresa).aggregate(Max('id_movimiento'))
	id_ant=mov_ant['id_movimiento__max']        
	if id_ant is None:
		aux = 1            
	else:
		aux=int(id_ant[-5:])+1
	correlativo = str(aux).zfill(5)
	codigo = str(empresa.codigo)+str(tipo.codigo)+str(anio)+str(zona.codigo)+correlativo
	return codigo

'''def obtener_codigo_orden(tipo, anio, mes, empresa):
	cursor = connection.cursor()
	query = "SELECT fn_getcodigoorden(%i,'%s','%s','%s')" % (tipo, anio, mes, empresa)
	cursor.execute(query)
	row = cursor.fetchone()
	return row[0]'''

def upload_file(request):
	if request.method == 'POST':
		form = UploadForm(request.POST, request.FILES)
		if form.is_valid():
			archivo = Archivo(docfile = request.FILES['docfile'])			
			archivo.save(form)
			csv_filepathname="media/"+str(archivo.docfile)
			dataReader = csv.reader(open(csv_filepathname), delimiter=',', quotechar='"')
			for fila in dataReader:
				cuenta = CuentaContable()
				cuenta.cuenta=fila[0]
				cuenta.descripcion=fila[1]
				cuenta.save()
			return HttpResponseRedirect(reverse('almacen:inicio'))
	else:
		form = UploadForm()
	return render(request, 'upload.html', {'form': form})

class Inicio(View):

	def get(self, request, *args, **kwargs):
		almacenes = Almacen.objects.all()
		if not almacenes:
			zonas = Zona.objects.all()
			if not zonas:
				return HttpResponseRedirect(reverse('almacen:crear_zona'))	 
			return HttpResponseRedirect(reverse('almacen:crear_almacen'))
		tipos_unidad = Tipo.objects.filter(tabla='tipo_unidad_medida')
		if not tipos_unidad:
			return HttpResponseRedirect(reverse('almacen:crear_tipo_unidad'))
		tipos_stock = Tipo.objects.filter(tabla='tipo_stock')
		if not tipos_stock:
			return HttpResponseRedirect(reverse('almacen:crear_tipo_stock'))
		cuentas = CuentaContable.objects.all()
		if not cuentas:
			return HttpResponseRedirect(reverse('almacen:upload_file'))
		grupos = GrupoSuministros.objects.all()
		if not grupos:
			return HttpResponseRedirect(reverse('almacen:crear_grupo_suministros'))
		suministros = Suministro.objects.all()	
		if not suministros:
			return HttpResponseRedirect(reverse('almacen:crear_suministro'))
		suministros_empresas = SuministroEmpresa.objects.all()
		if not suministros_empresas:
			return HttpResponseRedirect(reverse('almacen:registrar_inventario_inicial'))
		context = {'usuario': self.request.user}
		return render(request,'bienvenida.html', context)

class KardexSuministro(View):

	def get(self, request, *args, **kwargs):
		anios = Kardex.objects.datetimes('fecha_operacion', 'year')
		lista_anios = []
		for anio in anios:
			lista_anios.append(anio.year)
		meses = Kardex.objects.datetimes('fecha_operacion', 'month')
		lista_meses = []
		for mes in meses:
			lista_meses.append(mes.month)
		context = {'anios': lista_anios,'meses':lista_meses}
		return render(request,'kardex_suministro.html', context)

	def post(self, request, *args, **kwargs):
		mes = request.POST['meses']
		anio = request.POST['anios']
		cod_sumi = request.POST['codigo']
		suministro = Suministro.objects.get(codigo=cod_sumi)
		listado_kardex = Kardex.objects.filter(fecha_operacion__year=anio,fecha_operacion__month=mes,suministro=cod_sumi).order_by('suministro__descripcion','fecha_operacion','cantidads','fecha_registro')
		cantidade = listado_kardex.aggregate(Sum('cantidade'))
		cantidads = listado_kardex.aggregate(Sum('cantidads'))
		cantidadt = listado_kardex.aggregate(Sum('cantidadt'))
		valore = listado_kardex.aggregate(Sum('valore'))
		valors = listado_kardex.aggregate(Sum('valors'))
		valort = listado_kardex.aggregate(Sum('valort'))
		t_cantidad_e = cantidade['cantidade__sum']
		t_cantidad_s= cantidads['cantidads__sum']
		t_cantidad_t= cantidadt['cantidadt__sum']

almacen/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
	    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap-responsive.css">
	    <link type="text/css" href="/static/css/jquery-ui.css" rel="stylesheet" type="text/css" />
	    <link type="text/css" href="/static/css/jquery.appendGrid-1.5.1.css" rel="stylesheet"/>
	    <link type="text/css" href="/static/css/jquery-ui.structure.min.css" rel="stylesheet"/>
	    <link type="text/css" href="/static/css/jquery-ui.theme.min.css" rel="stylesheet" />
	    <script src="/static/js/jquery.js"></script>
	    <script src="/static/js/bootstrap.min.js"></script>
	    <script src="/static/js/jquery-ui.js"></script>
	    <script src="/static/js/jquery.ui.datepicker-es.js"></script>
	    <script src="/static/js/jquery.appendGrid-1.5.1.js"></script>
	    <script src="/static/js/jquery.numeric.js"></script>	    
	</head>
	<body>
		<div class="container">
			<div class="navbar navbar-fixed-top">
				<div class="navbar-inner">
					<div class="container">
						<a href="#" class="brand">MÓDULO DE ALMACEN</a>
						<ul class="nav pull-right">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">Operaciones<b class="caret"></b></a>
								<ul class="dropdown-menu" role="menu">
									<li><a href="{% url 'almacen:registrar_ingreso' %}">Registrar Ingreso</a></li>									
								</ul>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">Reportes<b class="caret"></b></a>
								<ul class="dropdown-menu" role="menu">
									<li><a href="{% url 'almacen:reporte_suministros' %}">Reporte de suministros</a></li>									
									<li><a href="{% url 'almacen:kardex_suministro' %}">Kardex por Suministro</a></li>									
								</ul>
							</li>														
							<li class="divider-vertical"></li>													
						</ul>						
					</div>

						
				</div>
			</div>
			<div class="row-fluid">
				<div class="span12">&nbsp;</div>
			</div>
			<div class="row-fluid">
				<div class="span12">&nbsp;</div>
			</div>
			{% block main_content %}
			{% endblock main_content %}
		</div>

		{% block js %}	
		{% endblock js %}

	</body>
</html>

almacen/templates/ingresar_movimiento.html
{% extends "base.html" %}

{% block main_content %}

	<form action="{% url 'almacen:registrar_ingreso' %}" method="post" class="form-control">
		{% csrf_token %}
		<legend>INGRESAR MOVIMIENTO</legend>		
		<div class="row-fluid">
			<div class="span3">
				TIPO DE INGRESO: 
				<select id="tipos_ingreso" name="tipos_ingreso">
					<option value="">Elija un tipo de ingreso</option>
					{% for tipo_ingreso in tipos_ingreso %}
						<option value="{{ tipo_ingreso.id }}">{{ tipo_ingreso.descripcion_valor }}</option>
					{% endfor %}}
				</select>
			</div>
			<div class="span3">
				ALMACEN: 
				<select id="almacenes" name="almacenes">
					<option value="">Elija un almacén</option>
					{% for almacen in almacenes %}
						<option value="{{ almacen.id }}">{{ almacen.descripcion }}</option>
					{% endfor %}}
				</select>
			</div>						
		</div>
		<div class="row-fluid">
			<div class="span3">
			Fecha<input type="text" name="fecha" id="fecha" readonly/><br />							
			</div>		
		</div>
		<div class="row-fluid">
			<div class="span3">
				DOC. REFER: 
				<select id="tipos_documento" name="tipos_documento">
					<option value="">Elija un documento</option>
					{% for tipo_documento in tipos_documento %}
						<option value="{{ tipo_documento.id_tabla_tipo  }}">{{ tipo_documento.descripcion_valor }}</option>
					{% endfor %}}
				</select>		
			</div>
			<div class="span3">
				SERIE<input type="text" name="serie" id="serie"/><br />							
			</div>
			<div class="span3">
				NUMERO<input type="text" name="numero" id="numero"/><br />							
			</div>
		</div>
		<div class="row-fluid">
		<br/>
		</div>		
		<div class="row-fluid">
			<div class="span12">
				<table id="tblDetalle"></table>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span4">
			</div>
			<div class="span4">
				 <input type="hidden" name="cdetalles" id="cdetalles" value="0"> 
				<input class="btn btn-primary" type="submit" id="guardar" name="guardar" value="Guardar Acta">
			</div>
		</div>			
	</form>

{% endblock main_content %}

{% block js %}
	<script>
	$(function () {
		$("#fecha").datepicker();
	});
	
	$('#tblDetalle').appendGrid({
        caption: 'DETALLE INGRESO',
        initRows: 0,
        columns: [
	        { name: 'id', display: 'ID Suministro', type: 'text', ctrlAttr: { 'readonly': 'readonly' }, ctrlCss: { width: '160px'} },
	        { name: 'suministro', display: 'Suministro', type: 'ui-autocomplete', 
	        uiOption: { source: "{% url 'almacen:busquedaSuministro' %}",minLength:3,select: 
	        	function (event, ui) 
	        	{
	        		var count =  $('#tblDetalle').appendGrid('getRowCount')-1;
	        		$('#tblDetalle').appendGrid('setCtrlValue', 'id', count, ui.item.id);
	        		$('#tblDetalle').appendGrid('setCtrlValue', 'unidad', count, ui.item.unidad);
	        		$('#tblDetalle').appendGrid('setCtrlValue', 'precio', count, ui.item.precio);
	        		var tcantidad = $('#tblDetalle').appendGrid('getCellCtrl', 'cantidad', count);
	        		var tprecio = $('#tblDetalle').appendGrid('getCellCtrl', 'precio', count);
	        		$(tcantidad).focus();
	        		$(tcantidad).numeric(".");
	        		$(tcantidad).keyup(function() {
						$('#tblDetalle').appendGrid('setCtrlValue', 'valor', count, tcantidad.value*tprecio.value);
					});					
	        		$(tprecio).numeric(".");
	        		$(tprecio).keyup(function() {
						$('#tblDetalle').appendGrid('setCtrlValue', 'valor', count, tprecio.value*tcantidad.value);
					});
            		return false;
            	}},
            	ctrlCss: { width: '400px'}
            },	
	        { name: 'unidad', display: 'Unidad', type: 'text', ctrlAttr: { 'readonly': 'readonly' }, ctrlCss: { width: '100px'} },
	        { name: 'cantidad', display: 'Cantidad', type: 'text', ctrlCss: { width: '100px'}},
	        { name: 'precio', display: 'Precio', type: 'text', ctrlAttr: { maxlength: 10 }, ctrlCss: { width: '100px', 'text-align': 'right' }, value: 0 },
	        { name: 'valor', display: 'Valor', type: 'text', ctrlAttr: { 'readonly': 'readonly' }, ctrlCss: { width: '100px', 'text-align': 'right' }, value: 0 }
            ]
    });	
	$("form" ).submit(function( event ) 
	{
		var cant_filas=$('#tblDetalle').appendGrid('getRowCount');
		var cont=0;
		$('#cdetalles').val(cont);
		if ($('#tipos_ingreso').val().trim() != '' && $('#almacenes').val().trim() != '') 
		{
			if($('#fecha').val().trim() != '')
			{
				if(cant_filas>0)
				{
					while(cont<cant_filas) 
					{
						var aux_id = $('#tblDetalle').appendGrid('getCellCtrl', 'id', cont);
						var aux_cant = $('#tblDetalle').appendGrid('getCellCtrl', 'cantidad', cont);
						if($(aux_id).val().trim() == '' || $(aux_cant).val().trim() == '')
						{
							alert("Complete los campos del detalle")
							event.preventDefault();
						}
						cont++;
					}
					return;	
				}				
			}
			else
			{
				alert("No ha seleccionado fecha")
			}			
		}
		else
		{
			alert("No ha seleccionado tipo de ingreso")
		}		
		event.preventDefault();
	});
   	
	</script>
{% endblock js %}

almacen/templates/kardex_suministro.html
{% extends "base.html" %}

{% block main_content %}

	<form action="{% url 'almacen:kardex_suministro' %}" method="post" class="form-control">
		{% csrf_token %}
		<legend>SELECCIONAR</legend>		
		<div class="row-fluid">
			<div class="span3">
				MES: 
				<select id="meses" name="meses">
					<option value="">Elija un mes</option>
					{% for mes in meses %}
						<option value="{{ mes }}">{{ mes }}</option>
					{% endfor %}}
				</select>
			</div>	
			<div class="span3">
				MES: 
				<select id="anios" name="anios">
					<option value="">Elija un año</option>
					{% for anio in anios %}
						<option value="{{ anio }}">{{ anio }}</option>
					{% endfor %}}
				</select>
			</div>					
		</div>
		<div class="row-fluid">
			<div class="span3">
				<div class="ui-widget">
					<label for="codigo">Codigo de Suministro: </label>
					<input id="codigo" name="codigo">
				</div>
			</div>
			<div class="span3">
				<div class="ui-widget">
					<label for="descripcion">Descripcion de Suministro: </label>
					<input id="descripcion" name="descripcion">
				</div>
			</div>
		</div>
		<div class="row-fluid">
		<br/>
		</div>		
		
		<div class="row-fluid">
			<div class="span4">
			</div>
			<div class="span4">
				 <input type="hidden" name="cdetalles" id="cdetalles" value="0"> 
				<input class="btn btn-primary" type="submit" id="guardar" name="guardar" value="VER REPORTE">
			</div>
		</div>			
	</form>

{% endblock main_content %}

{% block js %}
	<script>
	$(function() {
		$("#descripcion").autocomplete(
			{source: "{% url 'almacen:busquedaSuministro' %}",minLength:3,select: 
	        	function (event, ui) 
	        	{
	        		$('#codigo').val(ui.item.id);	        		
            		return false;
            	}});
	});
	</script>
{% endblock js %}